import 'package:flutter/material.dart';
import 'package:intl/intl.dart';
import 'package:provider/provider.dart';
import 'package:xeersoft_check_ins/helpers/SqfliteDbHelper.dart';
import 'package:xeersoft_check_ins/models/CheckInModel.dart';

class CheckInHistory extends StatefulWidget {
  final int userId;

  const CheckInHistory({
    super.key,
    required this.userId,
  });

  @override
  State<CheckInHistory> createState() => _CheckInHistoryState();
}

class _CheckInHistoryState extends State<CheckInHistory> {
  ValueNotifier<List<ReportCardViewModel>> items = ValueNotifier<List<ReportCardViewModel>>([]);
  ValueNotifier<List<ReportCardViewModel>> filteredItems = ValueNotifier<List<ReportCardViewModel>>([]);
  TextEditingController searchController = TextEditingController();
  ValueNotifier<List<CheckInModel>> checkInList = ValueNotifier<List<CheckInModel>>([]);
  ValueNotifier<int> selectedFilter = ValueNotifier<int>(0); // 0 - show all, 1 - missed, 2 - checked-in
  bool isAscending = true;

  @override
  void initState() {
    super.initState();
    registerListenerToTextController();
    initCheckInHistoryPage();
  }

  @override
  void dispose() {
    searchController.dispose();
    super.dispose();
  }

  Future<void> initCheckInHistoryPage() async {
    searchController.addListener(filterItems);
    WidgetsBinding.instance.addPostFrameCallback((_) {
      fetchCheckInHistoryList();
    });
  }

  void registerListenerToTextController() {
    searchController.addListener(() {setState(() {});});
  }

  void filterItems() {
    selectedFilter.value = 0;
    String query = searchController.text.toLowerCase();
    setState(() {
      filteredItems.value = items.value
          .where((item) => item.checkInDateTime.toLowerCase().contains(query))
          .toList();
    });
  }

  void sortItems() {
    selectedFilter.value = 0;
    searchController.clear();
    items.value.sort((a, b) => isAscending
        ? DateTime.parse(a.checkInDateTime).compareTo(DateTime.parse(b.checkInDateTime)) // Ascending order
        : DateTime.parse(b.checkInDateTime).compareTo(DateTime.parse(a.checkInDateTime)) // Descending order
    );
    filteredItems.value = items.value; // copy into filteredItems list
  }

  String getFormattedDateTime(String dateTime) {
    final date = DateTime.parse(dateTime);

    // Define the month names in Malay
    final monthNames = {
      1: 'Jan', 2: 'Feb', 3: 'Mar', 4: 'Apr', 5: 'May', 6: 'Jun',
      7: 'Jul', 8: 'Aug', 9: 'Sep', 10: 'Oct', 11: 'Nov', 12: 'Dec'
    };

    // Format the date and time
    final formattedDate = "${date.day} ${monthNames[date.month]} ${date.year}";
    final formattedTime = DateFormat('HH:mm:ss').format(date);
    return "Date: $formattedDate \nTime: $formattedTime.";
  }

  String getCheckInStatus(bool cStatus) {
    if (cStatus) {
      return "Checked-In";
    } else {
      return "Not Checked-In";
    }
  }

  List<ReportCardViewModel> _generateCompleteList(List<CheckInModel> existingCheckIns) {
    final now = DateTime.now();
    final currentDay = now.day;
    final lastDayOfMonth = DateTime(now.year, now.month + 1, 0).day;

    // Create a map of existing check-ins by day
    final existingCheckInMap = <int, CheckInModel>{};
    for (final checkIn in existingCheckIns) {
      final date = DateTime.parse(checkIn.checkInDateTime!);
      existingCheckInMap[date.day] = checkIn;
    }

    final mergedList = <ReportCardViewModel>[];

    for (int day = 1; day <= lastDayOfMonth; day++) {
      // Stop at current day (including today)
      if (day > currentDay) break;

      if (existingCheckInMap.containsKey(day)) {
        // Real check-in exists
        final checkIn = existingCheckInMap[day]!;
        mergedList.add(ReportCardViewModel(
          checkInId: checkIn.checkInId ?? 0,
          checkInDateTime: checkIn.checkInDateTime!,
          checkInStatus: checkIn.checkInStatus,
          isAutoGenerated: false,
        ));
      } else {
        // Generate missed check-in
        final date = DateTime(now.year, now.month, day);
        mergedList.add(ReportCardViewModel(
          checkInId: -day, // Negative ID for generated
          checkInDateTime: DateFormat('yyyy-MM-dd HH:mm:ss').format(date),
          checkInStatus: false,
          isAutoGenerated: true,
        ));
      }
    }

    return mergedList;
  }

  Future<void> fetchCheckInHistoryList() async {
    final loadingState = Provider.of<CheckInHistoryLoadingState>(context, listen: false);
    loadingState.setLoading(true);

    try {
      checkInList.value = await SqfliteDbHelper().getCheckInsByUserId(widget.userId);
      final completeList = _generateCompleteList(checkInList.value);

      items.value = completeList;
      filteredItems.value = List.from(completeList);
    } catch (e) {
      print("Error fetching report list: $e");
    } finally {
      sortItems();
      loadingState.setLoading(false);
    }
  }

  @override
  Widget build(BuildContext context) {
    TextTheme textTheme = Theme.of(context).textTheme;
    final loadingState = Provider.of<CheckInHistoryLoadingState>(context);

    return Scaffold(
      appBar: AppBar(
        title: Text("Check-In History",),
        centerTitle: true,
      ),
      body: RefreshIndicator(
        onRefresh: initCheckInHistoryPage,
        child: Stack(
          children: [
            Column(
              children: [
                // Search Bar and Sort Button
                Row(
                  children: [
                    Expanded(
                      child: Container(
                        margin: const EdgeInsets.fromLTRB(20, 20, 10, 10),
                        height: 50,
                        child: TextField(
                          controller: searchController,
                          decoration: InputDecoration(
                            hintText: 'Search...',
                            border: OutlineInputBorder(),
                            prefixIcon: searchController.text != ""
                                ? null
                                : IconButton(
                              icon: Icon(Icons.search),
                              onPressed: () {},
                            ),
                            suffixIcon: searchController.text == ""
                                ? null
                                : IconButton(
                              icon: Icon(Icons.clear),
                              onPressed: () {
                                searchController.clear();
                                filterItems();
                              },
                            ),
                          ),
                        ),
                      ),
                    ),
                    GestureDetector(
                      onTap: () {
                        setState(() {
                          isAscending = !isAscending; // Toggle sorting order
                        });
                        sortItems();
                      },
                      child: Container(
                        margin: const EdgeInsets.fromLTRB(10, 20, 20, 10),
                        width: 50,
                        height: 50,
                        decoration: BoxDecoration(
                          color: Colors.white,
                          borderRadius: BorderRadius.circular(10),
                          border: Border.all(color: Colors.black, width: 1),
                        ),
                        child: Icon(isAscending ? Icons.arrow_upward : Icons.arrow_downward),
                      ),
                    ),
                  ],
                ),
                // Total Records
                ValueListenableBuilder(
                    valueListenable: filteredItems,
                    builder: (context, value, child) {
                      return Container(
                        padding: const EdgeInsets.fromLTRB(20, 10, 20, 10),
                        alignment: Alignment.centerLeft,
                        child: Text("Total Records: ${filteredItems.value.length}"),
                      );
                    }
                ),
                // Filter Button
                ValueListenableBuilder(
                    valueListenable: selectedFilter,
                    builder: (context, value, child) {
                      return Container(
                        margin: EdgeInsets.only(left: 20, right: 20),
                        child: SingleChildScrollView(
                          scrollDirection: Axis.horizontal,
                          child: Row(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              ElevatedButton(
                                onPressed: () {
                                  searchController.clear();
                                  selectedFilter.value = 2;
                                  setState(() {
                                    filteredItems.value = items.value
                                        .where((item) => item.checkInStatus == true)
                                        .toList();
                                  });
                                },
                                style: ElevatedButton.styleFrom(
                                  backgroundColor: selectedFilter.value == 2
                                      ? Colors.green
                                      : null,
                                ),
                                child: Text(
                                  'Show Checked-In',
                                  style: TextStyle(
                                    color: selectedFilter.value == 2
                                        ? Colors.white
                                        : null,
                                  ),
                                ),
                              ),
                              SizedBox(width: 10),
                              ElevatedButton(
                                onPressed: () {
                                  searchController.clear();
                                  selectedFilter.value = 1;
                                  setState(() {
                                    filteredItems.value = items.value
                                        .where((item) => item.checkInStatus == false)
                                        .toList();
                                  });
                                },
                                style: ElevatedButton.styleFrom(
                                  backgroundColor: selectedFilter.value == 1
                                      ? Colors.red
                                      : null,
                                ),
                                child: Text(
                                  'Show Not Checked-In',
                                  style: TextStyle(
                                    color: selectedFilter.value == 1
                                        ? Colors.white
                                        : null,
                                  ),
                                ),
                              ),
                              SizedBox(width: 10),
                              ElevatedButton(
                                onPressed: () {
                                  searchController.clear();
                                  selectedFilter.value = 0;
                                  setState(() {
                                    filteredItems.value = List.from(items.value);
                                  });
                                },
                                style: ElevatedButton.styleFrom(
                                  backgroundColor: selectedFilter.value == 0
                                      ? Colors.blue
                                      : null,
                                ),
                                child: Text(
                                  'Show All',
                                  style: TextStyle(
                                    color: selectedFilter.value == 0
                                        ? Colors.white
                                        : null,
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      );
                    }
                ),
                // ListView without PageView
                ValueListenableBuilder(
                    valueListenable: filteredItems,
                    builder: (context, value, child) {
                      return Expanded(
                        child: filteredItems.value.isEmpty
                            ? SingleChildScrollView(
                          physics: AlwaysScrollableScrollPhysics(),
                          child: Center(
                            child: Padding(
                              padding: const EdgeInsets.all(16.0),
                              child: Text(
                                'No records found. Pull to refresh.',
                                textAlign: TextAlign.center,
                              ),
                            ),
                          ),
                        )
                            : ListView.builder(
                          padding: const EdgeInsets.fromLTRB(10, 5, 10, 5),
                          itemCount: filteredItems.value.length,
                          itemBuilder: (context, index) {
                            final item = filteredItems.value[index];

                            return Padding(
                              padding: const EdgeInsets.fromLTRB(10, 5, 10, 5),
                              child: Card(
                                key: ValueKey(item.checkInId),
                                color: Color(0xFFEAF0FB),
                                child: Container(
                                  padding: const EdgeInsets.fromLTRB(10, 15, 0, 15),
                                  color: Colors.transparent,
                                  child: Row(
                                    children: [
                                      Expanded(
                                        child: Column(
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          children: [
                                            Text(
                                              item.checkInDateTime,
                                              style: textTheme.bodyMedium!.copyWith(
                                                fontWeight: FontWeight.bold,
                                              ),
                                            ),
                                            SizedBox(height: 10,),
                                            Text(
                                              getFormattedDateTime(item.checkInDateTime),
                                              style: textTheme.bodyMedium,
                                            ),
                                            Text(
                                              getCheckInStatus(item.checkInStatus),
                                              style: textTheme.bodyMedium!.copyWith(
                                                color: item.checkInStatus ? Colors.green : Colors.red,
                                                fontWeight: FontWeight.bold,
                                              ),
                                            ),
                                          ],
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            );
                          },
                        ),
                      );
                    }
                ),
              ],
            ),

            // Show CircularProgressIndicator with a transparent background
            if (loadingState.isLoading)
              const Opacity(
                opacity: 0.5, // Set opacity to 0.5 for half transparency
                child: ModalBarrier(
                  dismissible: false, // Prevent dismissing by tapping outside
                  color: Colors.black, // Background color for the barrier
                ),
              ),

            if (loadingState.isLoading)
              const Center(
                child: CircularProgressIndicator(),
              ),
          ],
        ),
      ),
    );
  }
}

class CheckInHistoryLoadingState with ChangeNotifier {
  bool _isLoading = false;

  bool get isLoading => _isLoading;

  void setLoading(bool value) {
    _isLoading = value;
    notifyListeners();
  }
}

// model for the card
class ReportCardViewModel {
  int checkInId;
  String checkInDateTime;
  bool checkInStatus;
  final bool isAutoGenerated;

  ReportCardViewModel({
    required this.checkInId,
    required this.checkInDateTime,
    required this.checkInStatus,
    required this.isAutoGenerated,
  });
}